### ISSUE TITLE
NullPointerException in RealZoomableState

### ISSUE THREAD

**Issue by G00fY2** [saket/telephoto#93]
Seems like we run into the same crash as reported in #70

```
java.lang.NullPointerException
	at me.saket.telephoto.zoomable.RealZoomableState.fling-BMRW4eQ$zoomable_release(RealZoomableState.kt:502)
	at me.saket.telephoto.zoomable.ZoomableNode$onTransformStopped$1$1.invokeSuspend(Zoomable.kt:136)
```
First of all, thanks for this library. We tried to integrate telephoto one month ago (didn't found time to report this earlier) but unfortunately run into the same NPE already reported and marked as fixed with the following setup: AGP 8.4.1, Compose 1.6.8, telephoto 0.11.2, enableStrongSkippingMode=true

We used just used `ZoomableAsyncImage` to load the same images which we on other screens display by using coil's `SubcomposeAsyncImage`. So no special use case.

Our manual QA faced this crash right when they first tried the zoom functionality. So may it's not too hard to reproduce. Since our app is closed source and we replaced telephoto with https://github.com/usuiat/Zoomable (before releasing to production), I can not provide an sample project.

**Comment by saket** [comment]
> Our manual QA faced this crash right when they first tried the zoom functionality.

Can you share more details about your usage along with the steps your QA took to reproduce this crash?

**Comment by saket** [comment]
I think I have an idea about why this might be happening. Starting and ending a gesture before the content is initialized can cause a crash. I'll fix this scenario, but I'd still be interested in knowing how your QA team was reproducing the crash.

**Comment by G00fY2** [comment]
> Starting and ending a gesture before the content is initialized can cause a crash. I'll fix this scenario, but I'd still be interested in knowing how your QA team was reproducing the crash.

Hi @saket , cool that you already found the possible root cause. I just looked into the video of the crash provided by our QA and you seem to be right. The crash happened before the image finished loading/was displayed. So coincides with your suspected cause. 👍

**Comment by saket** [comment]
Fixed in `0.12.0`: https://github.com/saket/telephoto/releases/tag/0.12.0

**Comment by SimonMarquis** [comment]
A version of this crash is still happening on 0.13.0 with this stacktrace:

```
Fatal Exception: java.lang.NullPointerException
me.saket.telephoto.zoomable.RealZoomableState.fling-BMRW4eQ$zoomable_release (RealZoomableState.java:106)
me.saket.telephoto.zoomable.ZoomableNode$onTransformStopped$1$1.invokeSuspend (Zoomable.kt:106)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:9)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:93)
androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch (AndroidUiDispatcher.android.kt:15)
androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch (AndroidUiDispatcher.android.kt:15)
androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:10)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1103)
android.view.Choreographer.doCallbacks (Choreographer.java:896)
android.view.Choreographer.doFrame (Choreographer.java:810)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1090)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:201)
android.os.Looper.loop (Looper.java:288)
android.app.ActivityThread.main (ActivityThread.java:7886)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:568)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
```

Could this be an edge case where the gesture is cancelled (via the coroutine scope) while not having the gesture state entirely set up?
